### ISSUE TITLE
Builder APIs should be standardized

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#1019]
- The builder for `T` should be a nested interface `T.Builder` with a method `build()`.
- The method of `T` to obtain a copy builder should be named `copyBuilder()`, not `copy()` etc.
- Generic builder factory methods should be named `builder()` (if it is obvious for which type) or `tBuilder()`. Not `getTBuilder()`, `newTBuilder()` etc.
- Changes to conform to this rule should keep existing methods but deprecate them.

**Comment by nicost** [comment]
In addition, I highly prefer there to be instance methods to obtain a Builder, rather than a static method (or only a static method).  Reason for this is that the static methods make scripting harder.  At the very least, and import statement is needed, and it is quite difficult to discover where these are and what is needed, whereas an instance method makes an import unnecessary, and can be discovered easily through the documentation.  Example: "CoordsBuilder".  The deprecated method `cb = mm.data().getCoordsBuilder()` is much easier to work with than the: `import org.micromanager.data.Coordinates; cb = Coordinates.Builder();`

**Comment by marktsuchida** [comment]
Sounds good; the argument for scripting fluency is quite strong. I'll add `mm.data().coordsBuilder()` (keeping the name with `get` deprecated). Is this the only builder in need of a nonstatic method?

**Comment by nicost** [comment]
A not-thoroughly researched list:
- SequenceSettings
- PropertyMap
