### ISSUE TITLE
Add TeensySLM device adapter to build

### ISSUE THREAD

**Issue by henrypinkard** [micro-manager/micro-manager#1041]
I want to add the [TeensySLM](https://github.com/micro-manager/micro-manager/tree/master/DeviceAdapters/TeesnySLM) device adapter to be automatically built in nightlies. Shouldn't be hard to compile since it just uses serial commands and has no dependencies. Is there an easy way to do this without have to setup visual studio?

**Comment by nicost** [comment]
Done.

Please make updates to this code in the svn repository.  Updates there are propagated semi-automatically to 2.0.

The compiler showed the following warnings.  I always try to remove all compiler warnings (so that real problems stand out in the compiler output).  Could you have a look (most of these seem to only need commenting out variable names, but the address comparison looks sketchy):

2>  TeensySLM.cpp
2>c:\projects\micro-manager-1.4\deviceadapters\teesnyslm\TeensySLM.h(60): warning C4100: 'pixels' : unreferenced formal parameter
2>c:\projects\micro-manager-1.4\deviceadapters\teesnyslm\TeensySLM.h(77): warning C4100: 'blue' : unreferenced formal parameter
2>c:\projects\micro-manager-1.4\deviceadapters\teesnyslm\TeensySLM.h(77): warning C4100: 'green' : unreferenced formal parameter
2>c:\projects\micro-manager-1.4\deviceadapters\teesnyslm\TeensySLM.h(77): warning C4100: 'red' : unreferenced formal parameter
2>c:\projects\micro-manager-1.4\deviceadapters\teesnyslm\TeensySLM.h(84): warning C4100: 'interval_ms' : unreferenced formal parameter
2>c:\projects\micro-manager-1.4\deviceadapters\teesnyslm\TeensySLM.h(142): warning C4100: 'isSequenceable' : unreferenced formal parameter
2>c:\projects\micro-manager-1.4\deviceadapters\teesnyslm\TeensySLM.h(151): warning C4100: 'nrEvents' : unreferenced formal parameter
2>c:\projects\micro-manager-1.4\deviceadapters\teesnyslm\TeensySLM.h(192): warning C4100: 'pixels' : unreferenced formal parameter
2>c:\projects\micro-manager-1.4\deviceadapters\teesnyslm\TeensySLM.h(203): warning C4100: 'pixels' : unreferenced formal parameter
2>TeensySLM.cpp(315): warning C4800: 'long' : forcing value to bool 'true' or 'false' (performance warning)
2>  TeensyShutter.cpp
2>TeensyShutter.cpp(84): warning C4130: '!=' : logical operation on address of string constant
2>TeensyShutter.cpp(92): warning C4130: '!=' : logical operation on address of string constant
2>TeensyShutter.cpp(136): warning C4130: '!=' : logical operation on address of string constant
2>TeensyShutter.cpp(147): warning C4130: '!=' : logical operation on address of string constant
