### ISSUE TITLE
+ Zoom button does not work as expected with Preview window on second monitor

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#1072]
Reported by Falk on Image Forum: MM 2 nightly build 14-Dec-2020 19:53 (64bit)

Use case: Preview window is in live mode on 2nd monitor.
Pressing the ‘+’ zoom button does nor work as expected: The X direction is displayed kind of collapsed.

The ´+´zoom button works correct when preview window is on 1st monitor.

Related issue: #925 and #924, see PR #1031

**Comment by dangerousMoron** [comment]
I'd also like to report that I am  having this issue as well on the latest nightly build (20210116). Zooming in or out on the second display yields an extremely narrow view in the x-direction. This can be fixed by moving the preview window to the other display, or making it full screen. Attached is a picture of what this looks like. 

![narrow_x_micro_manager](https://user-images.githubusercontent.com/20504114/104851965-e7b5c280-58ac-11eb-9025-ae509fe264f1.png)
