### ISSUE TITLE
MMDevice Shared vs Static Runtime

### ISSUE THREAD

**Issue by nanthony21** [micro-manager/micro-manager#1122]
There are two projects for  MMDevice, "SharedRuntime" and "StaticRuntime". However, the Visual Studio projects for both of these are configured to compile as static .lib files.

Is it meant to be this way or this a mistake?

The only difference I see between the two projects is that the "StaticRuntime" has the following property defined: `<RuntimeLibrary>MultiThreadedDebug</RuntimeLibrary>`

**Comment by nicost** [comment]
Great questions!  @marktsuchida do you recall what these are and what they were/are for?

**Comment by marktsuchida** [comment]
Not a mistake, it is essential for the build to work. The difference is whether they link to a C++ standard library DLL (aka MultiThreaded[Debug]DLL, or the default) or to a static C++ standard library (aka MultiThreaded[Debug]). The vast majority of device adapters link to `MMDevice-SharedRuntime`, but some device adapters can only be built by linking to a static standard library because they link to other (vendor) libraries that also do so.

**Comment by nanthony21** [comment]
Thanks @marktsuchida.
