### ISSUE TITLE
ChannelSettings can not be removed from DisplaySettings

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#1247]
I can not find a way to remove channelSettings from DisplaySettings using the API (other than rebuilding the DisplaySettings from scratch).  

I needed this functionality as  I run into a strange bug where the DisplaySettings restored from profile contain more channels than the store, resulting in a display with extraneous channels (in this case, it suggests that there are multiple cameras in the configuration, which there are not).  @marktsuchida is there a clean way to deal with this?

**Comment by marktsuchida** [comment]
Looks like an API bug. `DisplaySettings.Builder` needs a method `Builder channels(Iterable<ChannelDisplaySettings> channelSettings)`, and passing `null` or an empty iterable/collection/list should clear all channels.

There could also be, if convenient, `Builder removeChannel(int channel)` and `Builder clearChannelSettings(int channel)` -- the former would remove the channel, shift any later indexed ones forward, and decrement numberOfChannels, whereas the latter would keep the channel but revert to the state equal to having been created with `channel(int channel)`. I suggest that both or neither of these be added, because having just one might be confusing.

**Comment by nicost** [comment]
Should we do that before release?  I know this goes against our API freeze, but we clearly need them to fix this (quite perplexing, I still do not understand it completely, and it is hard to reproduce) bug.

**Comment by marktsuchida** [comment]
I think fixing an API bug like this is okay.
