### ISSUE TITLE
Precompiled MMCore and MMDevice C++ libraries

### ISSUE THREAD

**Issue by zacharynevin** [micro-manager/micro-manager#1313]
Hi there,

I am finding it extremely difficult to do the source-code compilation for `MMCore` and `MMDevice` (from `mmCoreAndDevices`) on Windows 10. 

Are there any precompiled static or shared libraries available for this, for windows? I am writing a program that uses the C++ `MMDevice` and `MMCore` apis.

**Comment by marktsuchida** [comment]
No, we do not currently have pre-built binaries.

Which instructions are you following and what difficulty are you encountering?

MMDevice is only used as a static library (built into each device adapter as well as MMCore), but it should be easy to build it, because it has no external dependencies. Open `micromanager.sln`, open the project properties for the `MMDevice-SharedRuntime` project and set the Platform Toolset to `v142`. Right-click on the project and build.

MMCore can similarly be built, but requires Boost. A static library version of Boost is included in the `3rdpartypublic` svn repository. You can also use any appropriate Boost build if you modify the settings accordingly. We don't currently distribute MMCore except as a statically-linked component of MMCoreJ, its Java wrapper (and of pymmcore, which uses its own build system).

**Comment by zacharynevin** [comment]
Hi, 

I got `MMCore.lib` to compile! I had already downloaded the Windows 7 SDK and VS2010 etc, so I didn't need to change the platform toolset.

Thank you very much for all your help!

**Comment by marktsuchida** [comment]
You're welcome!
