### ISSUE TITLE
Make AcqJ available to MMStudio

### ISSUE THREAD

**Issue by henrypinkard** [micro-manager/micro-manager#1465]
[AcqEngJ](https://github.com/micro-manager/AcqEngJ) is more performant, flexible, and easier to change/improve than the current Clojure acquisition engine used by MMStudio. It is already used my Pycro-manager and Micro-Magellan. This issue describes adding it a back end to the Multi-dimensional Acquisition system in the Micro-Manager GUI, for now as an option in parallel with the current Clojure engine, but with the aim of eventually replacing and retiring that engine.

Doing so will provide many many immediate benefits, owing to shortcomings in the existing  Clojure acquisition engine and saving formats. Many of these limitations pointed out by @marktsuchida in https://github.com/micro-manager/mmCoreAndDevices/issues/180:

- Get rid of special treatment of position/time/Z indices. These can still be used, but aren't baked into the acquisition engine in the same way, making it easier to do more general experiments that vary along different axes.
- No circular dependencies on MMStudio. In fact, no dependencies on MMStudio at all (AcqEngJ sits above MMCoreJ only)
- The ability to use "Acquisition hooks" at various stages of the acquisition cycle, which enable injection of customized code that runs synchronously with the acquisition engine. More info on those [here](https://pycro-manager.readthedocs.io/en/latest/acq_hooks.html)
- A full syntax for instructions (acquisition events) that can be spelled out in JSON. This means experiments can be saved/loaded from files, or generated from GUI as it is now
- More transparent hardware sequencing behavior. Events get combined and can be printed to JSON before/during dispatch

Since AcqEngJ is much more flexible than the current engine, much of this will be straightforward and just require translation layers between our current ways of storing acquisition settings and the way AcqEngJ describes experiments (more on this below). One thing that comes to mind that still needs to be sorted out is:

- **Autofocus** is not built in an any way to AcqEngJ right now. Currently, in pycromanager people just do it through acquisition hooks. There will need to be some translation of the MDA settings for autofocus to make this work

#### Additional features that could be easily added
- More fine grained control over sequencing--e.g. run sequencing over z-stack, but not over channels
- Possible performance improvements. @marktsuchida mentioned `lazy sequence generation is inefficient`. Wondering if this is specific to Clojure engine or something more general
-  Better integration of [Pycro-Manager](https://github.com/micro-manager/pycro-manager), such that arbitrary python code could be injected into the acquisition cycle to synchronize hardware, or used to modify/divert images. 

### Some details on how to do it
(copied from #809, which I'm now closing)

A first step in this process would be to import use of AcqEngJ into the mmstudio codebase, so that it can be tested side-by-side with the existing engine until it is vetted enough to fully replace it. This will also require additions to AcqEngJ, such as support for autofocus. Right now, AcqEngJ is used in both the Java side of Pycro-Manager and Micro-Magellan. Both these projects use [NDViewer](https://github.com/micro-manager/NDViewer) as an image viewer and [NDTffStorage](https://github.com/micro-manager/NDTiffStorage) to save data, but the interfaces are entirely separated, so it should be possible to swap in the alternatives in mmstudio.

Practically this will involve:

1) Instantiating the new engine. This only needs to happen once.

```
import org.micromanager.acqj.internal.acqengj.Engine;
Engine engJ = new Engine(core);
```

2) Making an object that implements AcqEngJ's [DataSink](https://github.com/micro-manager/AcqEngJ/blob/master/src/main/java/org/micromanager/acqj/api/DataSink.java) interface. This might need to be an adapted class, or maybe there is an existing mmstudio class that already maps to this easily.

3) Extending or creating a class that has an instance of `org.micromanager.acqj.api.Acquisition`. This class takes `DataSink` as an argument, and must have the `initialize()` and then `start()` methods called on it. It's public API and documentation can be found in [org.micromanager.acqj.api.AcquisitionInterface](https://github.com/micro-manager/AcqEngJ/blob/master/src/main/java/org/micromanager/acqj/api/AcquisitionInterface.java)  

4) Tell the Acquisition what to acquire by calling `submitEventIterator` with an argument of an `Iterator<org.micromanager.acqj.api.AcquisitionEvent>`. Acquisition events correspond to the settings of a single image (i.e. one z slice on one channel). Submitting them as an iterator allows for the engine to do hardware sequencing, where applicable. One advantage of this system is that `AcqusitionEvents` can be serialized and deserialized using JSON, so acquisition instructions can come from code, a text file, or another programming language (e.g. Pycro-Manager). Convenience functions for doing this over time/z/channels/positions are already implemented (see [here](https://github.com/micro-manager/AcqEngJ/blob/master/src/main/java/org/micromanager/acqj/internal/acqengj/AcquisitionEventIterator.java) and [here](https://github.com/micro-manager/AcqEngJ/blob/master/src/main/java/org/micromanager/acqj/api/AcqEventModules.java)). Magellan's acquisition's provide a similar example of [how to do this](https://github.com/micro-manager/micro-manager/blob/d9be68288bd570e1204d8ead6e004483dd37fc30/plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanGUIAcquisition.java#L119).

5) Finally, finish the acquisition by calling `acquisition.finish()`

6) Maybe add a method to the studio API that automatically creates an acquisition with the settings present on the MDA window (if this doesn't already exist), so that external libraries (like Pycro-Manager) can create acquisitions with the MM GUI, but inject its own python-based image processors.

**Comment by marktsuchida** [comment]
Thanks for the writeup, @henrypinkard!

> * Adding it a back end to the Multi-dimensional Acquisition system in the Micro-Manager GUI, for now as an option in parallel with the current Clojure engine, but with the aim of eventually replacing and retiring that engine.

I 100% support this. I guess the question is what are the necessary API changes (if any)? Are you planning to add a new acquisition API, or keep the old one and make AcqEngJ handle it?

I think it is fine to have a new API (the acquisition API in MMStudio is an area we didn't renovate for 2.0 because we knew the engine had to change eventually, and didn't want to have a short-lived API). But the old API needs to continue to work, at least for a couple of years after the new one becomes full-featured, either by keeping the Clojure engine or by emulating it with AcqEngJ.

And if there is going to be a new API, what is it going to look like? Is AcqEngJ API going to be exposed directly, or will there be new MMStudio APIs that help interface with it?

If you intend for user code to use the AcqEngJ API directly, I might put some work into reviewing it before it becomes official, mostly just to make sure it is evolvable.

> * **Autofocus** is not built in an any way to AcqEngJ right now. Currently, in pycromanager people just do it through acquisition hooks. There will need to be some translation of the MDA settings for autofocus to make this work

Translating to hooks added to AcqEngJ sounds great. Probably cleaner than building into the engine.

> * @marktsuchida mentioned `lazy sequence generation is inefficient`. Wondering if this is specific to Clojure engine or something more general

I wasn't talking about a property of lazy sequences in general. The way lazy sequences are currently used in the Clojure engine is inefficient, because it unnecessarily creates an "acquisition event" object for each frame even if many such frames will simply be run as a single sequence acquisition. For example, if you want a simple 10000-frame time series, the Clojure engine first builds ("lazily") a sequence of 10000 acquisition events. Then it compares each successive event to find that no non-hardware-sequenceable changes occur between them, and merges them. This takes a lot of time if the number of frames is large. The laziness means that (if done correctly) it does not take up memory, but it still takes time to process all those events.

As for Phase 2, I think it's a whole separate discussion. I generally agree about the limitations you are trying to address. It helps to use very concrete examples of things that are currently hard to do and how (concretely) it would be done in the new system. At least that is how I think about these problems, and I think it helps when communicating them. The abstract description is necessary at some point, but it's hard to tell what real problems it is intended to solve (and which ones may be overlooked) without concrete use cases.

**Comment by nicost** [comment]
Quick testing with Demo Configuration:

1. Activate new AcqEng under Options.  Go to MDA window. Check "Channels". Click "New".  No new Channel appears.
2. Check "Z-Stacks", set up a Z stack with a few slices and run MDA.  Only two slices appear in the output.
3. Check only "Channels", check 3 channels. Only one image appears in  the output.
4. Check both "Time Points (5, 10 seconds apart), and "Multiple Positions" (4 positions), order Time, Position.  Acquisition happens instantly, i.e. all time points are acquired immediately.  If only "Time Points" is check, the interval is honored.

**Comment by nicost** [comment]
Items 1 and 2 are fixed in https://github.com/nicost/micro-manager/tree/acqEngJ.  Item 3 needs clarification about metadata handling in AcqEngJ (are channels handled by index or by name or both?).  Looking into item 4.

**Comment by nicost** [comment]
Addendum to item 4: with order Position, Time, the time lapse at the first position happens correctly, all subsequence ones are incorrect (there is no delay between the frames).

I believe items 3 and 4 can only be fixed in AcqEngJ.

**Comment by nicost** [comment]
I believe this can be closed with several recent updates.  The new AcqEngJ still needs more extensive testing, but most what I could test is working.

**Comment by henrypinkard** [comment]
Hooray!
