### ISSUE TITLE
mm2: Confusing behavior when histogram update rate = never

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#156]
When the last used setting is 'Never', no histograms are displayed for new images. This is a problem because (1) it is confusing (there should be some indication as to why no histogram is visible, so that the user can tell how to recover) and (2) it prevents the user from adjusting the intensity range (something that is possible even in 'Never' mode if the image started out with a histogram displayed).

One possibility (though not necessarily the best short-term fix) might be to replace the 'Never' mode with a 'Manual' mode. In manual mode, the histogram should be computed once (when the first image in that channel is displayed), and there should be a button that the user can click to update the histogram. This also has the advantage of giving an indication that the histogram is potentially stale.

**Comment by ChrisWeisiger** [comment]
This is now fixed -- the histogram UI will request histograms when it is created, but that request wasn't making it through to the code that actually calculates histograms, first due to a bug and second because updates were disabled. I fixed the bug, then changed the calculation logic to allow overriding of the disabled-updates for such manual requests. Thus when the UI creates itself, it requests histograms, and the display provides them; histograms are then not recalculated until and unless the histogram update rate is set to something else.

In lieu of implementing the manual mode proposed, the histograms now have a visual indicator (some text drawn on top of the histogram) that histogram updates are disabled.
