### ISSUE TITLE
Saving as NDTiff using the floppy disk icon in the viewer results in an error

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#1822]
Reproduced with the demo config.  Ran (any) MDA, press the floppy disk icon, select ND Tiff, and see fail.

**Comment by henrypinkard** [comment]
@nicost this appears to be caused by this check:

https://github.com/micro-manager/micro-manager/blame/f3d0faea760dd3e8e7459aee09f793d5b09ed424/mmstudio/src/main/java/org/micromanager/data/internal/DefaultDataSaver.java#L85

Removing the if statement makes this work for me, though Im hesitant to PR it because I don't really understand how this API is supposed to work and if it will break something else

**Comment by henrypinkard** [comment]
Related issue: https://forum.image.sc/t/null-pointer-exception-using-ndtiffdatastore-in-mm2/87355/2
