### ISSUE TITLE
mm2: Minor layout issues in main window

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#213]
The "Changroup" popup becomes wide when any of the config groups has a long name (this is probably not a bad thing in itself).

When that happens, (1) the "Shutter" panel does not expand horizontally. It should probably expand to take up the full width, with everything except for the label "Shutter" right-aligned.

(2) Also the ROI/Stage/Autofocus controls end up in a weird position. These can probably also be right-aligned within the available space.

**Comment by ChrisWeisiger** [comment]
The "Changroup" combobox growing huge always bothered me, so my fix for this issue is simply to provide a more "generous" minimum size for the combobox. If there's a long-named configuration group as the current channel group, then its name will get truncated, instead of blowing out the size of the combobox. The full name is of course visible in the config group pad just to the right of this control.
