### ISSUE TITLE
mm2 : Enable / Disable checkbox for Processors does not work

### ISSUE THREAD

**Issue by hadim** [micro-manager/micro-manager#248]
All is in the title.

I have tested it with all the plugin and also a customade plugin (FrameProcessor).

To disable a processor for now I need to remove it.

I couldn't find the source code associated to this action... sorry for that.

**Comment by ChrisWeisiger** [comment]
Thanks for the report. This has been fixed in 99478973195510d596f538a308e958594ea6f009. For reference, the checkbox was working for newly-created pipelines, but existing ones were not properly being recreated. If you'd closed the Snap/Live window and then re-opened it, it would have picked up the new pipeline.

**Comment by hadim** [comment]
Yeah sure I forgot to report the Snap/Lice trick I used.

Thanks
