### ISSUE TITLE
ROI button no longer draws a centered square at half the image size

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#309]
which is a big pity, since it was the only way to quickly and easily set an ROI at the center quadrant of the camera.  Any way to get the old behavior back (or an improvement on the old behavior?)

**Comment by marktsuchida** [comment]
Note that the "set ROI to center quad" is now a separate button (which does draw the selection), immediately to the right of the now "set ROI to selection" button.

The idea was to make it less confusing, because I've found myself explaining the complicated behavior of that single button over and over.

There should be an error message now if you click the "set ROI to selection" button without having a selection, so that users expecting the old behavior should not be confused.

**Comment by nicost** [comment]
Perfect!  I simply did not notice that there are now 3 buttons instead of 2.
