### ISSUE TITLE
mm2 Viewer: Time-Lapse animation restarts at time 0 after a time point was acquired

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#316]
While running an acquisition and playing back the time-lapse (by pressing the green arrow on the "t" icon), whenever a time point is acquired by the microscope, the animation restarts at time point 0 rather than at the time point it was when the acquisition of that time point started (or even better, at the time it would have been if the animation was not stopped.  This make it impossible to play back longer time lapse acquisitions while they are going on (which is very sad, because it is a lot of fun to watch these things while they are being acquired).

**Comment by ChrisWeisiger** [comment]
This should be fixed, though I can't promise the fix is absolutely perfect. There's a number of conflicting systems in play here for deciding what exactly the scrollbars should be doing, and it's exacerbated by the fact that each scrollbar is simultaneously a control (of which image should be displayed) and a display (of the coordinates of the displayed image). So making changes is a bit of a fraught process.

Still, the current behavior should at bare minimum be an improvement over what we have now.
