### ISSUE TITLE
MM2: acquisition settings bug for timeFirst and slicesFirst

### ISSUE THREAD

**Issue by julou** [micro-manager/micro-manager#535]
Hello,

with MM2beta-20170220, mm.acquisitions().getAcquisitionSettings().timeFirst equals true when the order is "postions, time, etc" and vice versa. This looks like a bug to me…

The same inversion occurs for mm.acquisitions().getAcquisitionSettings().slicesFirst
As far as I can say, the documentation doesnt mention that one should expect it to be inverted: https://valelab4.ucsf.edu/~MM/doc-2.0.0-beta/mmstudio/org/micromanager/SequenceSettings.html#slicesFirst

Best,
Thomas

**Comment by nicost** [comment]
Just ran into this again.  The description is correct, but easily misunderstood. The "Acquisition Engine" uses the timefirst and slicesFirst flags.  It does that more or less literary: when both flags are true, it takes the time points first (then moves to the next position, takes time points again), and slices first (then moves to the next channel, takes slices again).  

I was confused the exact same way, since timefirst suggest that time should be before position in the string with axes order, but it is the exact inverse.  

I am afraid this will stay confusing until we move completely to explicitly specified axes orders.
