### ISSUE TITLE
Perfect focus problem at multi-position acquisition

### ISSUE THREAD

**Issue by aaristov** [micro-manager/micro-manager#568]
Hi,

I've just started using v2.0 since 1.4 was too slow at long positions list.

My task is to acquire 300 consecutive frames at every step of 32x32 position list.

So your last build 2017-05-09 x64 features a bug switching on and off perfect focus (Nikon) at every position shift.  I also noticed there is no such bug in the previous build from 2017-05-08 x64. So it seems to be introduced just one day ago. It would be great to correct it. 

Many thanks!
Andrey

**Comment by nicost** [comment]
Hi Andrey,
There were no changes between 2017-05-08 and 09.  You can see that here: https://github.com/micro-manager/micro-manager/commits/mm2. Intriguingly, there is a 3 byte difference in size between the two installers, which I assume to be caused by automatically inserted date strings being compressed slightly differently.  Please note that if you happen to add the z-drive to the position list, then the PFS will automatically switch off when you move to a new position (this is a property of the Nikon TI stand, nothing that MM can do about it).  You have to be sure that z-position is not recorded.
