### ISSUE TITLE
getCurrentFrameCount method always returns 0

### ISSUE THREAD

**Issue by nanthony21** [micro-manager/micro-manager#652]
The getCurrentFrameCount of the the acquisitionwrapperengine always returns 0.

In addition to this is would be nice to have a way of know what position in the position list the acquisition is currently at.

**Comment by marktsuchida** [comment]
This method is not called anywhere in our code, is part of an internal interface (i.e. not API), and has an incorrect implementation. So I think it should just be deleted.

(Also because it's not clear if there is a correct way to implement this, given that everything is running asynchronously. I do agree that progress readout of the acquisition itself could be useful, but that will likely be addressed in a future acquisition engine.)
