### ISSUE TITLE
mmc.isBufferOverflowed() doesn't work

### ISSUE THREAD

**Issue by impact27** [micro-manager/micro-manager#819]
I am trying to use pycromanager  to control micromanager. I noticed that `isBufferOverflowed` doesn't work.

Using micromanager nightly build 20200527 and the default camera (with diagonal stripes, see attached) on Windows 10 pro.

![test](https://user-images.githubusercontent.com/6740194/83284663-4e328700-a1dd-11ea-886e-d61ce519c055.png)

 
Script :
```python
from pycromanager import Bridge
import time

#### Setup ####
#establish communication with Magellan
bridge = Bridge(convert_camel_case=False)
#get object representing micro-manager core
mmc = bridge.get_core()

print('Total Capacity:', mmc.getBufferTotalCapacity())
mmc.startContinuousSequenceAcquisition(0)
for i in range(20):
    time.sleep(1)
    print(mmc.getRemainingImageCount(), mmc.isBufferOverflowed())
```
I get the following output:
```
Total Capacity: 500
100 False
200 False
300 False
400 False
500 False
100 False
201 False
301 False
401 False
1 False
101 False
201 False
301 False
402 False
2 False
102 False
202 False
302 False
402 False
2 False
```
The buffer very clearly overflows.

**Comment by nicost** [comment]
It overflows, but the camera resets the buffer, and your code is never seeing the buffer as empty.  The assumption is that if the user wants the camera to run continuously, it is undesirable to stop when the buffer is full. So, the camera (device adapter) itself will reset the buffer once it is full.

To get bufferIsOverflowed return true, use:
`mmc.startSequenceAcquisition(600, 0, false)`
instead of 
`mmc.startContinuousSequenceAcquisition(0)`
